### PR TITLE
Fix PowerVS API endpoint special cases

### LINKED ISSUE #133: PowerVS API endpoint URL constructed incorrectly for some regions
The power cloud api endpoint cannot be reliably constructed using the CRN location.

e.g.: I just created a PowerVS instance with CRN of `crn:v1:bluemix:public:power-iaas:dal12:a/1fdf5effc3f945688c021cd0a8b45c4d:1c544998-1b20-45cf-acd8-44ee685d1839::`

The 'location' of `dal12` is parsed from this CRN (https://github.com/ManageIQ/manageiq-providers-ibm_cloud/blob/master/app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb#L16).

The correct endpoint location for this instance should be `us-south`.

We'll need to find a reliable way to get the endpoint from the GUID (hopefully something else from the resource controller API).

### PR DESCRIPTION
**Pull request by jaywcarman**
fixes #133 

This PR fixes two bugs related to Power Cloud API endpoints:
- The CRN 'location' segment sometimes includes regional zone enumerations and needs to be parsed to get the correct endpoint subdomain (e.g. `eu-de-1` uses the endpoint URL `https://eu-de.power-iaas.cloud.ibm.com`)
- #133: The CRN 'location' segment is sometimes totally different than the endpoint URL (e.g. `dal12` -> `https://us-south.power-iaas.cloud.ibm.com`)

### CODE REVIEW

File: app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb [hunk 1]
```diff
@@ -36,6 +36,19 @@ def connect(options = {})
...
+    api_endpoint_overrides = ::Settings.ems.ems_ibm_cloud_power_virtual_servers.api_endpoint_overrides
+
+    if api_endpoint_overrides.key?(location.to_sym)
+      url = api_endpoint_overrides[location.to_sym]
+    else
+      region = location.sub(/-\d$/, '')
+      url = "#{region}.power-iaas.cloud.ibm.com"
+    end
+
+    url
```
Comment (agrare) [inline app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb:49]: If you don't need to do anything else with the `url` here you can just do:
```
def api_endpoint_url(location)
    api_endpoint_overrides = ::Settings.ems.ems_ibm_cloud_power_virtual_servers.api_endpoint_overrides
  if api_endpoint_overrides.key?(location.to_sym)
    api_endpoint_overrides[location.to_sym]
  else
    region = location.sub(/-\d$/, '')
    "#{region}.power-iaas.cloud.ibm.com"
  end
end
```

Comment (agrare) [reply app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb:49]: Could even one-line it as `api_endpoint_overrides[location.to_sym] || "#{location.sub(/-\d$/, '')}.power-iaas.cloud.ibm.com"`

**Review by agrare — APPROVED** [review]
Anyway some possible refactorings but this looks good to me

**Comment by Fryguy** [comment]
Backported via https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/150
